apiVersion: v1
kind: Service
metadata:
  name: order-service
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "alb"  # or "alb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
